### ISSUE TITLE
Image display error

### ISSUE THREAD

**Issue by Raboro** [Canna71/obsidian-sheets#2]
In Obsidian the README.md file contains a image, but it is not shown:
![image](https://github.com/Canna71/obsidian-sheets/assets/88288557/9d4d2eae-4274-4268-a145-06a224eedfce)

But in your GH repo there is the image referenced, but  it contains a repo:
![image](https://github.com/Canna71/obsidian-sheets/assets/88288557/c470963a-4abf-4968-8bb5-a9548fe9672a)

But you named it: ``screen01.png``, because of that the image is not shown.
I can make a PR to change that or you can do this by your own.

**Comment by Canna71** [comment]
How did I miss it... thank you!
