### ISSUE TITLE
Problem: Hard to see the cursor in cell-editing

### ISSUE THREAD

**Issue by emisjerry** [Canna71/obsidian-sheets#4]
Hi, i cannot see input cursor while editing. Theme's problem?
I'm using v1.4.13 under Windows 11.

![image](https://github.com/Canna71/obsidian-sheets/assets/131511/62faac6e-e3ef-4234-89ee-57724748e6f5)

**Comment by Canna71** [comment]
Sorry, fixed style in 1.0.1
