### ISSUE TITLE
 can not export with pandoc

### ISSUE THREAD

**Issue by Juan-hwt** [Canna71/obsidian-sheets#5]
the plugin is amazing ... but can not export with pandoc to word, only in pdf 
when exporting ,table losted

**Comment by Canna71** [comment]
could you elaborate?

**Comment by Juan-hwt** [comment]
woooo ………… I reset obsidian, and after that it working ... thanks

**Comment by Juan-hwt** [comment]
woooo ………… I reset obsidian, and after that it working ... thanks
